chore: full court shot

diff --git a/.github/workflows/publish-old-local.yml b/.github/workflows/publish-old-local.yml
--- a/.github/workflows/publish-old-local.yml
+++ b/.github/workflows/publish-old-local.yml
@@ -1,5 +1,5 @@
 name: Build and Publish Docs for old versions
-
+# for testing CI on local machine use with act run >> act push -W .github/workflows/publish-old-local.yml
 on:
   push:
     branches:
@@ -15,11 +15,20 @@ jobs:
         version: ['2.6.0']
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          ref: react-magma-dom@${{ matrix.version }}
-      - name: Setup
+      - name: Setup for ACT
+        run: |
+          apt-get update && apt-get install sudo -y
+      - name: Install ACT dependencies
+        run: |
+          sudo apt-get install git jq -y
+
+      - name: Clone Repository
+        run: |
+          git clone https://github.com/cengage/react-magma.git .
+          git fetch --tags
+          git checkout react-magma-dom@${{ matrix.version }} || echo "Tag not found, continuing with main branch"
+
+      - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '18'
@@ -89,6 +98,9 @@ jobs:
           cd website/react-magma-docs
           CI=false SKIP_PREFLIGHT_CHECK=true DISABLE_ESLINT_PLUGIN=true gatsby build --verbose --prefix-paths || true
 
+        env:
+          PATH_PREFIX: /version/${{ matrix.version }}
+
       - name: Configure NPM
         run: |
           git config --global user.name 'github-bot'
@@ -99,6 +111,7 @@ jobs:
         run: |
           echo "::set-output name=alias::$(npm run --silent getAlias)"
           echo "::set-output name=version::$(npm run --silent getVersion)"
+
       - name: Deploy Docs to Netlify
         uses: nwtgck/actions-netlify@v1.1
         with:
